### ISSUE TITLE
Suggestion: document the fact that keys are important in sites.js

### ISSUE THREAD

**Issue by davidbgk** [zachleat/speedlify#15]
Given that keys in the JSON file lead to both links in the interface and slugs in URLs, I think it would be valuable to add a comment in that file for customization.

I realized that after the first deploy: https://github.com/davidbgk/speedlify/commit/9fed714941f32a7c91d73671db4bb09de9fd6dbe

By the way, great tool! 🙇

**Comment by zachleat** [comment]
Oh, good point! We should surface it in the options (and fall back to the key for backwards compat) to make it move obvious.

**Comment by davidbgk** [comment]
Maybe adding a link to the description [here](https://github.com/zachleat/speedlify/blob/live/index.njk#L16) would be useful too? (or hiding completely the `key` cell?)

**Comment by nhoizey** [comment]
IMHO, it would be nice having both a slug for URLs and a user friendly name to use in the UI (in the table on the homepage and in the title on the category page).

Current key is perfect for the slug, and we could add a `name` attribute.

**Comment by zachleat** [comment]
Added optional `name` value, which gets auto slugified. May add another slug option later but I don’t think it’s necessary yet
