### ISSUE TITLE
Private sites

### ISSUE THREAD

**Issue by Pedro-Souza** [zachleat/speedlify#18]
Is it possible to place to monitor on private websites? For example, a development environment that has a password.

Otherwise, do you find it interesting to add a resource for this?

**Comment by zachleat** [comment]
I probably won’t handle this use case, sorry—I just wouldn’t have very much use for it personally. The paid alternatives provide this feature though! https://www.zachleat.com/web/speedlify/#next-steps

**Comment by aanomm** [comment]
just a thought @Pedro-Souza
- netlify pro plans do enable password protected sites 
- they've also just significantly dropped the pricing of pro plans too —> [netlify.com/pricing](https://www.netlify.com/pricing/)
- i'm not sure if/how subdomains work with password protection though?
