### ISSUE TITLE
Strange behaviour using deply to netlify button

### ISSUE THREAD

**Issue by SteveALee** [zachleat/speedlify#22]
Build was slow so I looked aty the netilify log

"friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)"

then thought must be instramenting all *your* sites so I cancelled the deply and went to my speedlify repo on GitHub to edit- it is empty?

Surely the repo should be there even if I stopped the deploy?

**Comment by d2s** [comment]
Yeah, had similar experience previously. Had to stop the build process manually.
I had not realised that the default setup tests all of the sites
(spending a lot of the monthly free build capacity on Netlify).

Latest `README.md` version https://github.com/zachleat/speedlify/commit/20eb647693c36d1fe414e644688ad79bd391ec3d tells about the needed configuration changes.

> _After cloning you’ll probably want to delete the initial `_data/sites/*.js` files
> and create your own file with a list of your own site URLs!_

**Comment by zachleat** [comment]
Wow, really sorry about that! I added a `skip` option to the vertical configuration and it will now skip all of the default verticals when you clone. I also added a quick guide too

<img width="780" alt="image" src="https://user-images.githubusercontent.com/39355/88464577-98548380-ce81-11ea-922c-d45a9510080b.png">
