### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by httpsterio** [zachleat/speedlify#32]
I tried to find how the actual lists are sorted (ie. how the scores are weighted and compared against each other) and didn't really find it mentioned anywhere and I couldn't figure it out just by reading the code either. Any clarification possible?

**Comment by zachleat** [comment]
Ah yeah sorry the docs for this are not great yet! More info here https://www.zachleat.com/web/eleventy-leaderboard-speedlify/#“the-algorithm”-and-tiebreaker-changes

**Comment by httpsterio** [comment]
Alright, thanks for the clarification! I do understand why page weight plays into it but it feels counter intuitive that FCP and LCP don't factor in before page weight as currently this means that if the page hits 100s on Lighthouse and has no axe violations you should just increase the page size instead of optimizing the CSS and HTML and server settings.

Wouldn't it make more sense if the total blocking time would come before weight?

**Comment by zachleat** [comment]
I think it would make even more sense to allow a configuration option on `performance-leaderboard` specifically to feed in your own algorithm! Feel free to file an enhancement request over there!

**Comment by zachleat** [comment]
Sorry, here’s the thing https://github.com/zachleat/performance-leaderboard

**Comment by zachleat** [comment]
I’m operating under the assumption that you want to customize this for your own leaderboards, _not_ submit that the Eleventy Leaderboard algorithm be changed. Let me know if that’s wrong!
