### ISSUE TITLE
Detailed lighthouse and axe results

### ISSUE THREAD

**Issue by tctree333** [zachleat/speedlify#45]
Hello! Thanks for creating such a great tool. I've been playing around with speedlify for a bit to monitor some of my projects, and it would be very helpful if there was a way to see which lighthouse or axe tests were failing so I can try to fix them, at least for the latest run.

Right now, I'm checking the scores in speedlify, then running the tests again to see what's failing, and I think it would be helpful if that info could be shown. Would this be possible?

Thanks!

**Comment by zachleat** [comment]
I don’t think I have the resources to do this but the most recent raw output for the run is available in `.log`—note this current limitation: https://github.com/zachleat/performance-leaderboard/issues/5

Sorry about that!
