### ISSUE TITLE
Bump lighthouse version from 6.4.0 to 7.3.0 or 7.4.0?

### ISSUE THREAD

**Issue by ghost** [zachleat/speedlify#46]
I tried installing lighthouse 7.4.0 and it's there inside the node_modules but the reports still list the version as 6.4.0 making me think theres probably more to change than just the JSON files.

https://github.com/GoogleChrome/lighthouse/releases

**Comment by ghost** [comment]
looks like `performance-leaderboard@4.2.0` uses Lighthouse 7.3.0 but the reports still say 6.5.0 even though 4.2.0 is installed.
I'm currently manually overriding it using this:
`const lighthouse = require("./node_modules/lighthouse/lighthouse-core/index.js");`
with lighthouse 7.4.0 installed in `speedlify-live\node_modules\performance-leaderboard`

**Comment by zachleat** [comment]
This was updated awhile back, not quite sure when! But `performance-leaderboard` now matches major versions with Lighthouse (and is currently on 9)
