### ISSUE TITLE
"Deploy to Netlify" fails — NodeJS version < 14?

### ISSUE THREAD

**Issue by davidhund** [zachleat/speedlify#47]
"Deploy to Netlify" seems broken.

The Netlify Deploy fails `run-tests` with a SyntaxError because NodeJS 12 does not support the `?.` Optional chaining operator:

![image](https://user-images.githubusercontent.com/260518/145681575-635dea6d-ca2a-4355-9edb-6bdcdfb2607c.png)

There are many warnings before this, specifically:

```
npm WARN notsup Unsupported engine for lighthouse@9.1.0: wanted: {"node":">=14.15"} (current: {"node":"12.22.7","npm":"6.14.15"})
```

It seems the latest `"performance-leaderboard": "^9.0.0"` requires lighthouse ^9.0.0 which, in turn, requires NodeJS >= 14.15 but Netlify is running NodeJS 12.

I cannot see where we can/should update the NodeJS version Netlify Deploy should be using...

**Comment by davidhund** [comment]
FYI: I fixed this by changing NodeJS version `12` to `16` in my fork's `.nvmrc`

**Comment by zachleat** [comment]
Updated this, thanks!
