### ISSUE TITLE
Build with only 5 websites pages > Timeout on Netlify 

### ISSUE THREAD

**Issue by laurent-d** [zachleat/speedlify#51]
Hello,

After adding 2 websites pages to reach 5
I have Timeout issue on netlify build, before that all was good..

Any idea to avoid this issue ?
 An extract of the log 
 `Logged an error with https://website-702.eventmaker.io/:  LighthouseError [LHError]: PROTOCOL_TIMEOUT
10:33:43 PM:     at /opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/driver.js:341:50
10:33:43 PM:     at new Promise (<anonymous>)
10:33:43 PM:     at Driver.sendCommandToSession (/opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/driver.js:339:28)
10:33:43 PM:     at Driver.sendCommand (/opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/driver.js:362:17)
10:33:43 PM:     at ExecutionContext._evaluateInContext (/opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:109:42)
10:33:43 PM:     at ExecutionContext.evaluateAsync (/opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:146:25)
10:33:43 PM:     at async Function.afterPass (/opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:341:7)` 

Someone have an idea ?

**Comment by laurent-d** [comment]
Update of the issue, if someone get the same issue.
Time-out is due to heavy load of YouTube embed videos in my part.
Workaround to find > block YouTube for the test

**Comment by zachleat** [comment]
I might also recommend https://github.com/paulirish/lite-youtube-embed

works well on my site zachleat.com!

**Comment by laurent-d** [comment]
Honored of your reply @zachleat, You are a rockstar as Eleventy's father :) I use it since 2018..
For YT lite seems game changer in term of network load.
Thanks for your hard and smart works !!!
