### ISSUE TITLE
Speedlify on Netlify new issue on deploy .. Cache or Pupperter related

### ISSUE THREAD

**Issue by laurent-d** [zachleat/speedlify#59]
Hello,

Sorry for this message, i use speedlify for more than one year, 2 weeks ago builds become to failed with this errors :

4:03:36 PM: Using Ruby version 2.7.2
4:03:37 PM: Using PHP version 8.0
4:03:37 PM: Started restoring cached corepack dependencies
**4:03:37 PM: mv: cannot move '/opt/build/cache/.node/corepack' to '/opt/buildhome/.node/corepack': No such file or directory**
4:03:37 PM: Finished restoring cached corepack dependencies
4:03:37 PM: No npm workspaces detected
4:03:37 PM: Started restoring cached node modules
4:03:37 PM: Finished restoring cached node modules
4:03:37 PM: Bypassing sha validation. Running pre & post install scripts
4:03:37 PM: Installing npm packages using npm version 8.19.3
4:03:40 PM: added 20 packages, changed 3 packages, and audited 392 packages in 3s
4:03:40 PM: 63 packages are looking for funding
4:03:40 PM:   run `npm fund` for details
4:03:40 PM: found 0 vulnerabilities
4:03:40 PM: npm packages installed
4:03:40 PM: Started restoring cached go cache
4:03:40 PM: Finished restoring cached go cache
4:03:40 PM: Installing Go version 1.16.5 (requested 1.16.5)
4:03:45 PM: unset GOOS;
4:03:45 PM: unset GOARCH;
4:03:45 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64';
4:03:45 PM: export PATH="/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:${PATH}";
4:03:45 PM: go version >&2;
4:03:45 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.16.5.linux.amd64.env"
4:03:45 PM: go version go1.16.5 linux/amd64
4:03:46 PM: Detected 1 framework(s)
4:03:46 PM: "eleventy" at version "2.0.0-beta.2"
4:03:46 PM: Installing missing commands
4:03:46 PM: Verify run directory
4:03:46 PM: Section completed: initializing
4:03:47 PM: ​
4:03:47 PM:   Netlify Build                                                 
4:03:47 PM: ────────────────────────────────────────────────────────────────
4:03:47 PM: ​
4:03:47 PM: ❯ Version
4:03:47 PM:   @netlify/build 29.5.1
4:03:47 PM: ​
4:03:47 PM: ❯ Flags
4:03:47 PM:   baseRelDir: true
4:03:47 PM:   buildId: 63da7f3eb0cf91000a3b905d
4:03:47 PM:   deployId: 63da7f3eb0cf91000a3b9060
4:03:47 PM: ​
4:03:47 PM: ❯ Current directory
4:03:47 PM:   /opt/build/repo
4:03:47 PM: ​
4:03:47 PM: ❯ Config file
4:03:47 PM:   /opt/build/repo/netlify.toml
4:03:47 PM: ​
4:03:47 PM: ❯ Context
4:03:47 PM:   deploy-preview
4:03:47 PM: ​
4:03:47 PM: ❯ Loading plugins
4:03:47 PM:    - ./plugins/keep-data-cache@1.0.0 from netlify.toml
4:03:48 PM: ​
4:03:48 PM:   1. ./plugins/keep-data-cache (onPreBuild event)               
4:03:48 PM: ────────────────────────────────────────────────────────────────
4:03:48 PM: ​
4:03:49 PM: ​
4:03:49 PM: (./plugins/keep-data-cache onPreBuild completed in 295ms)
4:03:49 PM: ​
4:03:49 PM:   2. build.command from netlify.toml                            
4:03:49 PM: ────────────────────────────────────────────────────────────────
4:03:49 PM: ​
4:03:49 PM: $ npm run build-production
4:03:49 PM: > speedlify@1.0.0 build-production
4:03:49 PM: > npm run test-pages && npm run build && npm run zip-results
4:03:49 PM: > speedlify@1.0.0 test-pages
4:03:49 PM: > node run-tests
**4:03:50 PM: /opt/build/repo/node_modules/performance-leaderboard/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:127
4:03:50 PM:                     throw new Error(`Could not find Chromium (rev. ${this.puppeteer.browserRevision}). This can occur if either\n` +
4:03:50 PM:                     ^
4:03:50 PM: Error: Could not find Chromium (rev. 1083080). This can occur if either**
4:03:50 PM:  1. you did not perform an installation before running the script (e.g. `npm install`) or
4:03:50 PM:  2. your cache path is incorrectly configured (which is: /opt/buildhome/.cache/puppeteer).
4:03:50 PM: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
4:03:50 PM:     at ChromeLauncher.resolveExecutablePath (/opt/build/repo/node_modules/performance-leaderboard/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:127:27)
4:03:50 PM:     at ChromeLauncher.executablePath (/opt/build/repo/node_modules/performance-leaderboard/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:205:25)
4:03:50 PM:     at PuppeteerNode.executablePath (/opt/build/repo/node_modules/performance-leaderboard/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:162:105)
4:03:50 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/performance-leaderboard/performance-leaderboard.js:7:50)
4:03:50 PM:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
4:03:50 PM:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
4:03:50 PM:     at Module.load (node:internal/modules/cjs/loader:1043:32)
4:03:50 PM:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
4:03:50 PM:     at Module.require (node:internal/modules/cjs/loader:1067:19)
4:03:50 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
4:03:50 PM:     at require (node:internal/modules/cjs/helpers:103:18)
4:03:50 PM: ​
4:03:50 PM:   "build.command" failed 

I read that the website of this repo run fine ... thx to https://www.speedlify.dev/
But on my side without any changes excepted a "click on retry to build without cache" it not work anymore.

Someone have an idea about this new issue ?

**Comment by zachleat** [comment]
We did ship a new `performance-leaderboard` in the last week or so https://github.com/zachleat/performance-leaderboard/

Is that causing problems?

**Comment by laurent-d** [comment]
Hello thanks @zachleat for the reply,

Yes it's seems, i fixed my package.json to stick on v9.6.3 of performance-leaderboard..

And now all seems good again :)
