### ISSUE TITLE
Rename _data/sites.js to _data/sites-sample.js

### ISSUE THREAD

**Issue by nhoizey** [zachleat/speedlify#7]
When updating a fork, `_data/sites.js` should be the only file with legitimate changes to keep, so renaming it to `_data/sites-sample.js` in the source repository would allow easier forks updates.

Speedlify could look for `sites-sample` data if there is no `sites` data, and add a big notification in the UI (like Eleventy's documentation button… 😅) to invite people to create their own `sites.js` file.

**Comment by nhoizey** [comment]
You could even **not** look for `sites-sample` data, if you don't want everyone to check Netlify pages… 😅

**Comment by zachleat** [comment]
Hmm. HMM. This is all I have to say right now hmm—not sure I like that but I’m not the one feeling the pain of the conflicts 😅

**Comment by nhoizey** [comment]
> Hmm. HMM.

I'll take that for now… 😅

We can wait for additional feedback from other users.

**Comment by davidbgk** [comment]
I agree that it would ease the pain of merging to keep the code in sync when forking. It would probably require a changelog, at least for that file though.

**Comment by zachleat** [comment]
I pushed a change to speedlify that will help here and probably will be good enough to close this one. Each category/vertical is now a separate file in `_data/sites/*.js` so we shouldn’t see conflicts here moving forward unless you have the same categories as me 👍🏻

**Comment by nhoizey** [comment]
This is even better! 👍
