### ISSUE TITLE
What do I need to do to tell Netlify to build this periodically?

### ISSUE THREAD

**Issue by NickColley** [zachleat/speedlify#8]
I've managed to get my own fork published! So cool. How do I tell Netlify to build it every day?

**Comment by NickColley** [comment]
Or if it's literally just 'press the netlify rebuild button' if you want a new one, that's cool too.

**Comment by zachleat** [comment]
I use IFTTT, here’s my applet with my webhook url removed

![image](https://user-images.githubusercontent.com/39355/86267064-c0efa300-bb8b-11ea-92ad-4b0924caee33.png)

**Comment by NickColley** [comment]
Ah okay, thought there might be a thing built into Netlify. Thank you!!

**Comment by nhoizey** [comment]
I also used IFTTT before for this, but I now use a Github Action so the configuration is in the same code repository.

I followed instructions here: https://ericjinks.com/blog/2019/netlify-scheduled-build/
